spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    username: vishal1
    password: Leegality@123
    jpa:
      properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate.ddl-auto: update
      generate-ddl: true
      show-sql: true
